// ALERT
export const ADD_ALERT = 'ADD_ALERT';

// LOADING
export const TOGGLE_LOADING = 'TOGGLE_LOADING';

// LOGIN
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REFRESHTOKEN = 'REFRESHTOKEN';

// ENUNS
export const LOAD_ROLES = 'LOAD_ROLES';
export const LOAD_STATES = 'LOAD_STATES';
export const LOAD_CONTACT_TYPES = 'LOAD_CONTACT_TYPES';
export const LOAD_LEASE_TYPES = 'LOAD_LEASE_TYPES';

// USER
export const EDIT_USER_DETAILS = 'EDIT_USER_DETAILS';
export const EDIT_USER_SETTINGS = 'EDIT_USER_SETTINGS';
export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE';
export const EDIT_USER_PASSWORD = 'EDIT_USER_PASSWORD';

// USERS
export const CREATE_USER = 'CREATE_USER';
export const EDIT_USER = 'EDIT_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const LOAD_USERS = 'LOAD_USERS';

// CUSTOMERS
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER';
export const LOAD_CUSTOMERS = 'LOAD_CUSTOMERS';
export const LOAD_CUSTOMER = 'LOAD_CUSTOMER';

// CONTACTS
export const CREATE_CONTACT = 'CREATE_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const REMOVE_CONTACT = 'REMOVE_CONTACT';
export const LOAD_CUSTOMER_CONTACTS = 'LOAD_CUSTOMER_CONTACTS';

// CONTRACTS
export const CREATE_CONTRACT = 'CREATE_CONTRACT';
export const EDIT_CONTRACT = 'EDIT_CONTRACT';
export const REMOVE_CONTRACT = 'REMOVE_CONTRACT';
export const LOAD_CONTRACTS = 'LOAD_CONTRACTS';

// PLACES
export const CREATE_PLACE = 'CREATE_PLACE';
export const EDIT_PLACE = 'EDIT_PLACE';
export const REMOVE_PLACE = 'REMOVE_PLACE';
export const LOAD_PLACES = 'LOAD_PLACES';
