// ALERT
export const CREATE_ALERT = 'CREATE_ALERT';

// LOADING
export const UPDATE_LOADING = 'UPDATE_LOADING';

// LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';

// ENUNS
export const SET_ROLES = 'SET_ROLES';
export const SET_STATES = 'SET_STATES';
export const SET_CONTACT_TYPES = 'SET_CONTACT_TYPES';
export const SET_LEASE_TYPES = 'SET_LEASE_TYPES';
export const SET_ADDITIONAL_REQUIRED_TYPES = 'SET_ADDITIONAL_REQUIRED_TYPES';

// USER
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const UPDATE_USER_SETTINGS = 'UPDATE_USER_SETTINGS';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';

// USERS
export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const SET_USERS = 'SET_USERS';

// CUSTOMERS
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const SET_CUSTOMERS = 'SET_CUSTOMERS';
export const SET_CUSTOMER = 'SET_CUSTOMER';

// CONTACTS
export const ADD_CONTACT = 'ADD_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const SET_CONTACTS = 'SET_CONTACTS';

// CONTRACTS
export const ADD_CONTRACT = 'ADD_CONTRACT';
export const UPDATE_CONTRACT = 'UPDATE_CONTRACT';
export const DELETE_CONTRACT = 'DELETE_CONTRACT';
export const SET_CONTRACTS = 'SET_CONTRACTS';

// PLACES
export const ADD_PLACE = 'ADD_PLACE';
export const UPDATE_PLACE = 'UPDATE_PLACE';
export const DELETE_PLACE = 'DELETE_PLACE';
export const SET_PLACES = 'SET_PLACES';

// ADDITIONALS
export const ADD_ADDITIONAL = 'ADD_ADDITIONAL';
export const UPDATE_ADDITIONAL = 'UPDATE_ADDITIONAL';
export const DELETE_ADDITIONAL = 'DELETE_ADDITIONAL';
export const SET_ADDITIONALS = 'SET_ADDITIONALS';